CREATE DATABASE dbFieis;

use dbFieis;

CREATE TABLE Fiel(
idFiel INT NOT NULL AUTO_INCREMENT,
nome CHAR(30) NOT NULL,
CPF CHAR(11) NOT NULL,
email CHAR(100),
telefone CHAR(11)NOT NULL,

CONSTRAINT PK_idFiel PRIMARY KEY Fiel(idFiel)
CONSTRAINT UK_CPF UNIQUE KEY Fiel(CPF)
);

